# Generated by Django 4.2.2 on 2023-07-03 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="catgory",
            new_name="category",
        ),
    ]
