# Generated by Django 4.2.2 on 2023-07-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_rename_catgory_room_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
