# Generated by Django 4.2.2 on 2023-07-07 21:38

from django.db import migrations, models
import room.models
import room.validators


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0003_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=room.models.room_banner_upload_path,
                validators=[room.validators.validate_image_file_extension],
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=room.models.room_icon_upload_path,
                validators=[
                    room.validators.validate_icon_image_size,
                    room.validators.validate_image_file_extension,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True, null=True, upload_to=room.models.category_icon_upload_path
            ),
        ),
    ]
